name: "HiveMQ-Edge"
description: "HiveMQ edge is a MQTT broker for IoT at the edge, MQTT bridging and advanced protocol conversion to MQTT."
version: "1.1.6"
slug: "hivemq"
init: false
arch:
  - aarch64
  - amd64

url: https://github.com/floresboy/HA-addon-MQTT
startup: services


ingress: true
ingress_port: 8080
ingress_stream: true



ports:
  1883/tcp: 1883
  8080/tcp: 8080
  2442/udp: 2442

panel_icon: mdi:pipe
panel_title: HiveMQ-Edge

map:
  - ssl
options:
  env_vars: []
host_network: true
schema:
  env_vars:
    - name: match(^HMQ_([A-Z0-9_])+$)
      value: str
